@proxyUrl = http://localhost:7950
@rosettaUrl = http://localhost:8091
@baseNetwork = localnet

###

POST {{rosettaUrl}}/account/balance HTTP/1.1
Content-Type: application/json

{
  "network_identifier": {
    "blockchain": "Elrond",
    "network": "{{baseNetwork}}"
  },
  "block_identifier": {
    "index": 42
  },
  "account_identifier": {
        "address": "erd1spyavw0956vq68xj8y4tenjpq2wd5a9p2c6j8gsz7ztyrnpxrruqzu66jx"
  },
  "currencies": [
      {
          "symbol": "XeGLD",
          "decimals": 18
      }
  ]
}
