from pathlib import Path

PATH_REPOSITORY = Path(__file__).parent.parent
PATH_ROSETTA = PATH_REPOSITORY / "cmd" / "rosetta" / "rosetta"
PATH_PROXY_TO_OBSERVER_ADAPTER = PATH_REPOSITORY / "systemtests" / "proxyToObserverAdapter"
PORT_ROSETTA = 7091
URL_OBSERVER_SURROGATE = "http://localhost:8080"
ADAPTER_DELAY_IN_MILLISECONDS = 80
ADDITIONAL_GAS_LIMIT_FOR_RELAYED_V3 = 50_000
AWAITING_POLLING_TIMEOUT_IN_MILLISECONDS = 1000
AWAITING_PATIENCE_IN_MILLISECONDS = 0
