name: Automatic auditing (proxy workflow)

on:
    pull_request:
    workflow_dispatch:

permissions:
    contents: read

jobs:
    forward-request:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger automatic auditing
              env:
                  GH_TOKEN: ${{ secrets.MX_AUTO_AUDIT_WORKFLOWS }}
              run: |
                  REPOSITORY=${{ github.event.repository.name }}
                  BRANCH=${{ github.head_ref || github.ref_name }}

                  gh workflow run semgrep_ce.yml --repo multiversx/mx-auto-audit --ref init -f repository=$REPOSITORY -f branch=$BRANCH
