name: golangci-lint
on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  golangci:
    name: golangci linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v6
        with:
          go-version: 1.26.2
      - uses: actions/checkout@v6
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.12.2

          # Optional: golangci-lint command line arguments.
          args: --timeout 10m0s --max-issues-per-linter 0 --max-same-issues 0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
