name: Regularly check testnet

on:
    workflow_dispatch:
    schedule:
        - cron: "0 */2 * * *"

jobs:
    check-testnet:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/setup-python@v5
              with:
                  python-version: 3.11

            - uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                  pip install -r ./requirements-dev.txt
                  curl -sSfL https://raw.githubusercontent.com/coinbase/mesh-cli/master/scripts/install.sh | sh -s -- -b "$HOME/.local/bin"
                  echo "$HOME/.local/bin" >> $GITHUB_PATH

            - name: Build
              run: |
                  cd $GITHUB_WORKSPACE/cmd/rosetta && go build .
                  cd $GITHUB_WORKSPACE/systemtests && go build ./proxyToObserverAdapter.go

            - name: check:data
              run: |
                  python3 ./systemtests/check_with_mesh_cli.py --mode=data --network=testnet
              env:
                  PYTHONPATH: .
